# Use `just <recipe>` to run a recipe
# https://just.systems/man/en/

# Aliases

alias fmt := format

# Add git commit hashes to the .git-blame-ignore-revs file
[group('linter')]
add-git-blame-ignore-revs:
    git log --pretty=format:"%H" --grep="^lint" >> .git-blame-ignore-revs
    sort .git-blame-ignore-revs | uniq > .git-blame-ignore-revs.tmp
    mv .git-blame-ignore-revs.tmp .git-blame-ignore-revs

# Format all files using pre-commit
[group('linter')]
format args='':
    # Make sure obsolete hook file gets deleted
    rm -f .git/hooks/pre-commit.legacy
    pre-commit run --all-files {{ args }}
