# Use `just <recipe>` to run a recipe
# https://just.systems/man/en/

# Aliases

alias fmt := format

# Add git commit hashes to the .git-blame-ignore-revs file
[group('linter')]
add-git-blame-ignore-revs:
    git log --pretty=format:"%H" --grep="^lint" >> .git-blame-ignore-revs
    sort .git-blame-ignore-revs | uniq > .git-blame-ignore-revs.tmp
    mv .git-blame-ignore-revs.tmp .git-blame-ignore-revs

# Format all files using pre-commit
[group('linter')]
format args='':
    prek run --all-files {{ args }}

# Remove legacy git hooks
[group('git')]
remove-legacy-git-hooks:
    rm -rf .git/hooks/*.legacy
